apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: tibians
spec:
  type: LoadBalancer
  ports:
  - name: mongodb-port
    port: 27017
    targetPort: 27017
    protocol: TCP
  - name: mongo-express
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: mongodb_server