apiVersion: apps/v1
kind: Deployment
metadata:
  name: tibia-mongodb-deployment
  namespace: tibians
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb_server
  template:
    metadata:
      labels:
        app: mongodb_server
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret123
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: localhost
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: root
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: secret123
