apiVersion: batch/v1
kind: Job
metadata:
  name: tibia-item-id-mongodb-loader
  namespace: tibians
spec:
  template:
    spec:
      containers:
      - name: tibia-item-id-mongodb-loader
        image: gacerioni/tibia_item_id_mongodb_loader:latest
        {{- if or .Values.env.config .Values.env.secrets}}
        envFrom:
        {{- if .Values.env.config}}
        - configMapRef:
            name: {{.Values.name}}
        {{- end}}
        {{- if .Values.env.secrets}}
        - secretRef:
            name: {{.Values.name}}
        {{- end}}
        {{- end}}
      restartPolicy: OnFailure
  backoffLimit: 4