name: tibia-item-id-api
replicas: 1

image: ${artifact.metadata.image}
dockercfg: ${artifact.source.dockerconfig}

createNamespace: true
namespace: ${infra.kubernetes.namespace}

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName
serviceType: LoadBalancer

# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
servicePort: 8000
serviceTargetPort: 8000

# Specify all environment variables to be added to the container.
# The following two maps, config and secrets, are put into a ConfigMap
# and a Secret, respectively.
# Both are added to the container environment in podSpec as envFrom source.
env:
  config:
    TESTGABS: PALMEIRAS
  secrets:
    TIBIA_API_MONGODB_USR: ${serviceVariable.tibia_api_mongodb_usr}
    TIBIA_API_MONGODB_PWD: ${serviceVariable.tibia_api_mongodb_pwd}
    TIBIA_API_MONGODB_HOST: tibia-item-id-api-mongodb-svc:27017